### ISSUE TITLE
an appropriate `README.md` file

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sd-factory#36]
References for Catena-X in descriptions should be replaced by Eclipse Tractus-X like in [this example](https://github.com/eclipse-tractusx/sd-factory/blob/c71182b414dc314ed5acf03127081ae9b529aa42/README.md?plain=1#L3).

**Comment by almadigabor** [comment]
There are a lot more catena-x references in this document. I provided that as an example.

**Comment by adkumar1** [comment]
@dvasunin : Please check
