### ISSUE TITLE
an appropriate `INSTALL.md`

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sd-factory#37]
[Repo name](https://github.com/eclipse-tractusx/sd-factory/blob/c71182b414dc314ed5acf03127081ae9b529aa42/INSTALL.md?plain=1#L11) `sd-factory` in the `helm repo add` command in invalid compared to the next 2 commands.

**Comment by adkumar1** [comment]
This has been taken care with f72a95bed12e420a76d27af9fbb590007e5971ce

**Comment by almadigabor** [comment]
Added review [comment ](https://github.com/eclipse-tractusx/sd-factory/pull/38#pullrequestreview-1411791993) to PR#38
